# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b8188a4a4942606494ef7fd2d56ec785ccc94854802d0c2f7a8d9b11ed27f539cdfeed0c0a93dfd2e9d2b00668b9aaad109e7a59a3799c82ebec9ce97b0cf7c

test:
  secret_key_base: c34ada2eda72c83c5235757e72b9c4ee7c262f0febd401683863db9fabbb69db027a90036ba3942fe70de36267ee5c2437f6b8c177d950e0d80f76c40d303e2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 9b86eafd006236672c6a9bc910f5a1b2df4aa93e205e7b4fbcab5683d4755d86e174d5c7fde8838c5f1002f7b4021f718acd560bced2687d54a78b5961514ff8
